name: Build and push to dockerhub
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get release tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          DOCKER_BUILDKIT: 1
        with:
          name: opensentry/meui
          dockerfile: Dockerfile.alpine
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
